### PR TITLE
 * Added support for cfgPath

### PR DESCRIPTION
**Pull request by eemmiirr**
Please merge after https://github.com/alexec/docker-java-orchestration/pull/24

### CODE REVIEW

**Comment by alexec** [comment]
Hi,

Do you think you could add an integration test for this? I want to make sure that the feature does not get broken anytime in the future? Also, do you want to add yourself to the CONTRIB.md file?

Alex

**Comment by eemmiirr** [comment]
Hi,

Yes sure I will do it the following days.

Kind regards,
Emir

**Comment by eemmiirr** [comment]
I am actually trying to write tests but I get always 'https protocol is not supported' on ITs even i put it to http. Do you maybe know what the cause of that.

**Comment by alexec** [comment]
Do you have DOCKER* env set? If so, what are they?

**Comment by eemmiirr** [comment]
Sorry my bad forgot to set DOCKER_URL

**Comment by eemmiirr** [comment]
Somehow managed to write the tests. Could you please merge this after https://github.com/alexec/docker-java-orchestration/pull/35 was merged

**Comment by eemmiirr** [comment]
seems to work now had to increase the sleep of nginx to 180000ms since it's building some keys for ssl. Unfortunately this is needed

**Comment by eemmiirr** [comment]
The change works. The tests are passing just at the end of the build some other failure is happening.

```
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy (default-deploy) on project docker-maven-plugin: Failed to deploy artifacts: Could not transfer artifact com.alexecollins.docker:docker-maven-plugin:jar:2.8.6-20150519.163905-14 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/alexecollins/docker/docker-maven-plugin/2.8.6-SNAPSHOT/docker-maven-plugin-2.8.6-20150519.163905-14.jar. Return code is: 401, ReasonPhrase: Unauthorized.
```

**Pull request merged**
